version: '3.7'

services:
  front-foodsquare:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: front-foodsquare
    volumes:
      - .:/home/app/front-foodsquare
    working_dir: /home/app/front-foodsquare
    ports:
      - 3021:3021
    restart: always
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
